// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/auth.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServiceTest {
  internal static partial class Auth
  {
    static readonly string __ServiceName = "auth.Auth";

    static readonly grpc::Marshaller<global::GrpcServiceTest.LoginRequest> __Marshaller_auth_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServiceTest.LoginReply> __Marshaller_auth_LoginReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.LoginReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServiceTest.EventInfoRequest> __Marshaller_auth_EventInfoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.EventInfoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServiceTest.EventInfoReply> __Marshaller_auth_EventInfoReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.EventInfoReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcServiceTest.LoginRequest, global::GrpcServiceTest.LoginReply> __Method_Login = new grpc::Method<global::GrpcServiceTest.LoginRequest, global::GrpcServiceTest.LoginReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_auth_LoginRequest,
        __Marshaller_auth_LoginReply);

    static readonly grpc::Method<global::GrpcServiceTest.EventInfoRequest, global::GrpcServiceTest.EventInfoReply> __Method_EventInfo = new grpc::Method<global::GrpcServiceTest.EventInfoRequest, global::GrpcServiceTest.EventInfoReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EventInfo",
        __Marshaller_auth_EventInfoRequest,
        __Marshaller_auth_EventInfoReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServiceTest.AuthReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Auth</summary>
    [grpc::BindServiceMethod(typeof(Auth), "BindService")]
    public abstract partial class AuthBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcServiceTest.LoginReply> Login(global::GrpcServiceTest.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcServiceTest.EventInfoReply> EventInfo(global::GrpcServiceTest.EventInfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Auth</summary>
    public partial class AuthClient : grpc::ClientBase<AuthClient>
    {
      /// <summary>Creates a new client for Auth</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuthClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Auth that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuthClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuthClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuthClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcServiceTest.LoginReply Login(global::GrpcServiceTest.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcServiceTest.LoginReply Login(global::GrpcServiceTest.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.LoginReply> LoginAsync(global::GrpcServiceTest.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.LoginReply> LoginAsync(global::GrpcServiceTest.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::GrpcServiceTest.EventInfoReply EventInfo(global::GrpcServiceTest.EventInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EventInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcServiceTest.EventInfoReply EventInfo(global::GrpcServiceTest.EventInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EventInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.EventInfoReply> EventInfoAsync(global::GrpcServiceTest.EventInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EventInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.EventInfoReply> EventInfoAsync(global::GrpcServiceTest.EventInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EventInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuthClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_EventInfo, serviceImpl.EventInfo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcServiceTest.LoginRequest, global::GrpcServiceTest.LoginReply>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_EventInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcServiceTest.EventInfoRequest, global::GrpcServiceTest.EventInfoReply>(serviceImpl.EventInfo));
    }

  }
}
#endregion
