// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/echo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServiceTest {
  public static partial class Echo
  {
    static readonly string __ServiceName = "echo.Echo";

    static readonly grpc::Marshaller<global::GrpcServiceTest.EchoRequest> __Marshaller_echo_EchoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.EchoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServiceTest.EchoReply> __Marshaller_echo_EchoReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServiceTest.EchoReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcServiceTest.EchoRequest, global::GrpcServiceTest.EchoReply> __Method_Echo = new grpc::Method<global::GrpcServiceTest.EchoRequest, global::GrpcServiceTest.EchoReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Echo",
        __Marshaller_echo_EchoRequest,
        __Marshaller_echo_EchoReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServiceTest.EchoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Echo</summary>
    [grpc::BindServiceMethod(typeof(Echo), "BindService")]
    public abstract partial class EchoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcServiceTest.EchoReply> Echo(global::GrpcServiceTest.EchoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Echo</summary>
    public partial class EchoClient : grpc::ClientBase<EchoClient>
    {
      /// <summary>Creates a new client for Echo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EchoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Echo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EchoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EchoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EchoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcServiceTest.EchoReply Echo(global::GrpcServiceTest.EchoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Echo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcServiceTest.EchoReply Echo(global::GrpcServiceTest.EchoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Echo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.EchoReply> EchoAsync(global::GrpcServiceTest.EchoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServiceTest.EchoReply> EchoAsync(global::GrpcServiceTest.EchoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Echo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EchoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EchoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EchoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Echo, serviceImpl.Echo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EchoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Echo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcServiceTest.EchoRequest, global::GrpcServiceTest.EchoReply>(serviceImpl.Echo));
    }

  }
}
#endregion
